[project]
name = "configurator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiconfigurator>=0.9.0",
    "beautifulsoup4>=4.15.0",
    "requests>=2.34.2",
    "transformers>=5.12.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.18",
]

[tool.uv.sources]
configurator = { workspace = true }
