target-version = "py314"
line-length = 88
indent-width = 4



[lint.pydocstyle]
convention = "google"



[format]
preview = true
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true

exclude = [
  "./.cache",
  "./.git",
  "./.idea",
  "./.mypy_cache",
  "./.pytest_cache",
  "./.venv",
  "./venv",
  "./env",
  "./cached_venv",
  "./docs",
  "./var",
  "./.vscode",
]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "RET", # flake8-return
    "RSE", # flake8-raise
    "PIE", # flake8-pie
    "PTH", # flake8-use-pathlib
    "PT",  # flake8-pytest-style
    "RUF", # ruff-specific rules
]

extend-select = ["E", "F", "I", "UP", "B", "W", "C90", "N", "D", "PYI", "PT", "RET", "SIM", "ARG", "ERA"]
ignore = [
  "B008",
  "C901",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D203",
  "D205",
  "D213",
  "COM812",
  "E501",
  "ERA001",
  "N802",
  "PT017"
]

[lint.isort]
lines-after-imports = 2
lines-between-types = 1
no-lines-before = ["future", "standard-library"]
no-sections = false
order-by-type = true


[lint.per-file-ignores]
"test_*.py" = ["S101"]
"tests.py" = ["S101"]
"tests_*.py" = ["S101"]
"tests/*" = ["S101", "ARG001", "ARG002"]
"conftest.py" = ["S101", "ARG001", "ARG002"]
"__init__.py" = ["F401", "F403"]